### ISSUE TITLE
Request: Variable Heights & more biome support

### ISSUE THREAD

**Issue by InkDragon** [baileyholl/Terrain-Crystals#1]
requesting an option to control the height of the islands

Would also like to know if more biomes will be added, if not could they be?

**Comment by DrasticDemise** [comment]
Can you clarify what you mean by height? If you are referencing how far down the island expands in a spike, yes. 

I have opened up two more issues for the Swamp and Jungle biomes and will look to their addition.

**Comment by InkDragon** [comment]
yup, I'd like to be able to control how far down an island's spike goes. I'd like to be able to mimic the tcon slime islands in style.

also if possible could there be an ocean biome? the crystal would create the normal outer shape with dirt/clay and then the inside would be filled with water.

**Comment by DrasticDemise** [comment]
Both biomes added - am unable to change variable height without a complete rewrite.

**Comment by InkDragon** [comment]
Thank you, just please keep it in mind should you ever need to do a rewrite
