### ISSUE TITLE
Feature request; void biome exclusive override

### ISSUE THREAD

**Issue by Deshiba** [baileyholl/Terrain-Crystals#16]
I would like the functionality to make crystals capable of changing the void biome exlusively. So that for instance the void can be changed to swamp, but swamp can not be changed to ice spikes.

This would mainly be used for skyblock worlds.

**Comment by baileyholl** [comment]
In minecraft there is no "void" biome. Void worlds have biome lines and behavior-limited behaviors in the areas of the map of that biome, there is simply no land to go along with it.  I can add a config option to specify which biome type is acceptable to transform by ID, but the uses don't seem evident as one main feature of the mod is to be able to create your own biome lines in any shape you want.

**Comment by Deshiba** [comment]
This is confusing. When in the game on the "Void" preset generated by the custom map type the biome does show as "Void" in  the F3 screen. It also seems to have it's own id set to 127 (Source: minecraft.gamepedia.com/Biome#Other_biomes)

If it can be done it'd be nice, but if it's outside the scope I can find another way ;)

**Comment by baileyholl** [comment]
Hmm. I was under the impression, unless this has changed recently, that there was no such thing as a void biome (given, I haven't played modded MC since 1.7.10). It clearly exists so I can add this in, interesting find!

The other question is, if the "void" biome depicted in the picture generates that structure, is the entire world of void biome or only that section?

**Comment by Deshiba** [comment]
The void was added in 1.9, http://minecraft.gamepedia.com/1.9#World_generation:

> Superflat
>     New preset: The Void
>         Spawns the player on a stone platform. No other terrain generates.
>         The Void is now a biome with an ID of 127.

When generated in game the entire world is the void biome, except other dimensions.

**Comment by baileyholl** [comment]
Cool, I will implement this with next update.

**Comment by baileyholl** [comment]
Done!
