### ISSUE TITLE
Feature request; Restriction feedback

### ISSUE THREAD

**Issue by Deshiba** [baileyholl/Terrain-Crystals#21]
When the restrictions for dimensions are set to true as below, there is no feedback in game. This (probably) results in players not knowing what is going on (when playing with this mod in a pack).

"End Crystal Restricted to End Dimension"=true
"If The Nether Crystal only works in the Nether"=true

Would it be possible to add feedback in one or both of the following ways?
* A chat message telling players "This crystal can only be used in the [Nether||End].
* A description added to the crystal, possibly in red;
**Terrain Crystal: Nether
**Can only be used in the Nether.
**Relog for client sync.

**Comment by baileyholl** [comment]
Yep, will be added to both crystals.
