### ISSUE TITLE
Tree spawning frequency in plains

### ISSUE THREAD

**Issue by Deshiba** [baileyholl/Terrain-Crystals#25]
Currently the plains spawn trees with a frequency fitting for a forest rather then a plains. http://i67.tinypic.com/288cjl4.png

Possible solutions:
- Configurable frequency for Fauna spawns to occur (possibly per crystal).
- Splitting the tree generation function to a Forest Crystal.

**Comment by baileyholl** [comment]
Lowered to 1% chance per block, similar to the savanna crystal now. Dramatically improved. Enjoy!
